### ISSUE TITLE
Problem when running on Windows 7

### ISSUE THREAD

**Issue by niunno** [ishmael1985/gstreamer-media-SDK#23]
I installed the plugin on:
- PC with i7-7700 and Windows 7 Embedded 64-bit service pack 1;
- PC with i7-7700 and Windows 7 Pro 32-bit service pack 1;
- PC with Xeon ES-1620, which has not an embedded GPU, and Windows 7 Pro 64-bit service pack 1.

All the installations went ok, but when I ran
`gst-inspect-1.0.exe mfx`
all the systems prompt the error 
> api-ms-win-shcore-scaling-l1-1-1.dll is missing

**Comment by ishmael1985** [comment]
@niunno Windows 7 is not supported. Even if we can fix this issue, which is mainly due to missing dependencies in your setup. The main problem is that even if you fix your setup issue, you will encounter driver limitations for Windows 7.
You can try your luck if you wish - https://docs.microsoft.com/en-us/windows/desktop/direct3darticles/platform-update-for-windows-7

**Comment by niunno** [comment]
Thank you very much. I've looked carefully at the requirements at it was specified:
> DirectX 11 (Windows 8 / 8.1 / 10)

**Comment by niunno** [comment]
Just a question; if I wanted to test the plugin with the platform update, would I have to recompile the plugin or save the DLL somewhere?

**Comment by ishmael1985** [comment]
Nope
