### ISSUE TITLE
Any reason why meson.build file was removed on windows branch ?

### ISSUE THREAD

**Issue by boxerab** [ishmael1985/gstreamer-media-SDK#37]

**Comment by ishmael1985** [comment]
The 'windows' branch was intended as another option for users to build the plugins under Visual Studio IDE instead of Meson, so including Meson build files shouldn't be done if the user will build it with Visual Studio anyway. In fact, if I need to build the plugins for 32-bit Windows, this is the branch I use.

**Comment by boxerab** [comment]
Thanks for the explanation!
